drop table if exists higawari;
create table higawari(
    id integer primary key autoincrement,
    time string not null,
    a string not null,
    b string not null,
    c string not null,
    d string not null,
    e string not null,
    f string not null,
    d1 string not null,
    d2 string not null,
    d3 string not null,
    e1 string,
    e2 string,
    e3 string,
    vote_a integer defalut "0",
    vote_b integer defalut "0",
    vote_c integer defalut "0",
    vote_d integer defalut "0",
    vote_e integer defalut "0",
    vote_f integer defalut "0",
    vote_d1 integer defalut "0",
    vote_d2 integer defalut "0",
    vote_d3 integer defalut "0",
    vote_e1 integer defalut "0",
    vote_e2 integer defalut "0",
    vote_e3 integer defalut "0"
);
